---
apiVersion: v1
kind: Namespace
metadata:
  name: pod

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: busybox
  name: busybox
  namespace: pod
spec:
  containers:
    - image: busybox:1.34.1
      name: busybox
      args:
      - "sleep"
      - "100000"
