---
apiVersion: v1
kind: Namespace
metadata:
  name: statefulset

---
apiVersion: v1
kind: Service
metadata:
  name: sts-svc
  namespace: statefulset
  labels:
    app: statefulset
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: statefulset

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
  namespace: statefulset
spec:
  selector:
    matchLabels:
      app: statefulset # has to match .spec.template.metadata.labels
  serviceName: "statefulset"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: statefulset # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: registry.k8s.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local
      resources:
        requests:
          storage: 1Gi
