---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts1
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/sts1"
  persistentVolumeReclaimPolicy: Retain #! host_path deleter only supports /tmp/.+ but received provided /data/sts1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts2
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/sts2"
  persistentVolumeReclaimPolicy: Retain #! host_path deleter only supports /tmp/.+ but received provided /data/sts1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sts3
  labels:
    type: local
spec:
  storageClassName: local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/sts3"
  persistentVolumeReclaimPolicy: Retain #! host_path deleter only supports /tmp/.+ but received provided /data/sts1
