---
apiVersion: v1
kind: Namespace
metadata:
  name: resource-limits


---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-ranges
  namespace: resource-limits
spec:
  limits:
  - default: # this section defines default limits
      cpu: 100m #millicore 1000m = 1core
      memory: 256Mi #Mébioctet utilisée en stockage 1MiB (binaire 2^x) = 1Mo (décimal 10^x) = 1 048 576 octets
    defaultRequest: # this section defines default requests
      cpu: 100m
      memory: 256Mi
    max: # max and min define the limit range
      cpu: "2"
      memory: 1Gi
    min:
      cpu: 100m
      memory: 256Mi
    type: Container

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: resource-limits
spec:
  hard:
    cpu: "1000"
    memory: 2Gi
    pods: "5"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-limit-ranges
  namespace: resource-limits
  labels:
    app: limit-ranges
spec:
  replicas: 2
  selector:
    matchLabels:
      app: limit-ranges
  template:
    metadata:
      labels:
        app: limit-ranges
    spec:
      containers:
        - image: busybox:1.34.1
          name: busybox
          args:
          - "sleep"
          - "100000"
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
