---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: sa-demo-clusterrole
rules:
- apiGroups: [""]
  #
  # at the HTTP level, the name of the resource for accessing pods
  # objects is "pods"
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
