---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: auth
  name: sa-demo-role
rules:
- apiGroups: [""] # "" indicates the core API group
  #
  # at the HTTP level, the name of the resource for accessing pods
  # objects is "pods"
  resources: ["pods"]
  verbs: ["get", "watch", "delete", "patch", "update", "list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles","rolebindings"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]
