---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: sa-demo-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: sa-demo # Name is case sensitive
  namespace: auth
roleRef:
  kind: ClusterRole
  name: sa-demo-clusterrole
  apiGroup: rbac.authorization.k8s.io