---
apiVersion: v1
kind: Namespace
metadata:
  name: auth

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-demo
  namespace: auth
#Monte automatiquement les pods déployés avec le serviceaccount
automountServiceAccountToken: false


