---
apiVersion: v1
kind: Namespace
metadata:
  name: service-account


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-demo
  namespace: service-account
#Monte automatiquement les pods déployés avec le serviceaccount
automountServiceAccountToken: false


