---
apiVersion: v1
kind: Namespace
metadata:
  name: deployment

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanform
  namespace: deployment
  labels:
    app: deploy-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-demo
  template:
    metadata:
      labels:
        app: deploy-demo
    spec:
      containers:
      - name: kanform-pyproject
        image: kanform/python-project:v1.2

---
apiVersion: v1
kind: Service
metadata:
  name: kanform-svc
  namespace: deployment
spec:
  selector:
    app: deploy-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32000
  type: NodePort
