apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kanforms-ns.kanform.io
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental"
spec:
  group: "kanform.io"
  names:
    kind: kanform-managed-ns
    plural: kanforms-ns
    singular: kanform-ns
    shortNames:
    - kns
    - kanns
    - kfns
    - kfmns
    - kmns
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              team:
                type: string
              quotas:
                type: object
                properties:
                  cpu:
                    type: integer
                    minimum: 200
                    maximum: 4000
                  memory:
                    type: integer
                    minimum: 256
                    maximum: 2000
              expire:
                type: string