---
apiVersion: v1
kind: Namespace
metadata:
  name: daemonset

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-demo
  namespace: daemonset
  labels:
    app: ds-demo
spec:
  selector:
    matchLabels:
      name: ds-demo
  template:
    metadata:
      labels:
        name: ds-demo
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: nginx
        image: nginx:1.23.0

