---
apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: replicaset

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  namespace: replicaset
  labels:
    app: nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-rs
  template:
    metadata:
      labels:
        app: nginx-rs
    spec:
      containers:
      - name: nginx
        image: nginx:1.22.1
